ALTER TYPE "Role" RENAME VALUE 'ADMIN' TO 'SUPER_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'TENANT_ADMIN';

ALTER TABLE "User" ADD COLUMN "numberId" TEXT;

CREATE UNIQUE INDEX "User_numberId_key" ON "User"("numberId");

ALTER TABLE "User"
ADD CONSTRAINT "User_numberId_fkey"
FOREIGN KEY ("numberId") REFERENCES "WhatsAppNumber"("id")
ON DELETE SET NULL ON UPDATE CASCADE;
